project:
  type: website
  output-dir: docs

website:
  title: "Icons of the mountains"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - text: "Projects"
        menu:
          - projects.qmd
          - student_projects.qmd
          - information_students.qmd
      - posts.qmd  
  page-footer: 
    border: true
    left: "Contact: erlend.b.nilsen@nord.no / jan.e.ostnes@nord.no"
    center: 
      - href: https://osf.io/yt63w/
        text: "Open Science Framework"
    right: 
      - icon: github
        href: https://github.com/MountainIcons

format:
  html:
    theme: slate
    linkcolor: darkorange
    css: styles.css
    toc: true

editor: visual

